#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
   path: /inicio
   controller: App\Controller\HomeController::index

animales:
   path: /animales/{nombre?}/{apellidos?}
   controller: App\Controller\HomeController::animales   
   defaults: {"nombre":"patata","apellidos":"petete"}
   methods: [POST,GET]

